name: Build

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v2
        with:
          name: nucleoid-datapack
          path: |
            data/
            pack.mcmeta
          retention-days: 30
